# Generated by Django 6.0.3 on 2026-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('day', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=50)),
                ('examDate', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subjectId', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
