# Generated by Django 6.0.3 on 2026-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_priority_availability_user_material_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
